const EXAM={scored:75,pretest:5,minutes:150,pass:73,fee:'$395',outlineDate:'October 2025',functions:[['1','Collection, analysis and evaluation of data',49,37],['2','Underwriting, new financing, offerings and registration',27,20],['3','M&A, tender offers and restructuring',24,18]]};
const sources={
exam:'https://www.finra.org/registration-exams-ce/qualification-exams/series79',
outline:'https://www.finra.org/sites/default/files/2025-10/Series_79_Content_Outline.pdf',
rule1220:'https://www.finra.org/rules-guidance/rulebooks/finra-rules/1220',
sie:'https://www.finra.org/registration-exams-ce/qualification-exams/securities-industry-essentials-exam',
validity:'https://www.finra.org/registration-exams-ce/qualification-exams/exam-credit-validity',
mabroker:'https://www.sidley.com/en/insights/newsupdates/2023/03/us-congress-exempts-certain-merger-and-acquisition-brokers-from-sec-broker-dealer-registration',
nasaa:'https://www.nasaa.org/adopted-model-rule/registration-exemption-for-certain-merger-acquisition-brokers/model-rule-exempting-certain-merger-and-acquisition-brokers-from-registration-_5-6-2024/',
ibba:'https://www.ibba.org/wp-content/uploads/2025/04/business-broker-state-licensing-list.pdf',
regd:'https://www.sec.gov/resources-small-businesses/exempt-offerings/general-solicitation-rule-506c',
r144:'https://www.investor.gov/introduction-investing/investing-basics/glossary/rule-144-selling-restricted-and-control-securities',
tender:'https://www.sec.gov/rules-regulations/staff-guidance/corporation-finance-interpretations/tender-offer-rules-schedules',
tender2026:'https://www.ropesgray.com/en/insights/alerts/2026/04/sec-cuts-minimum-tender-offer-period-in-half-for-equity-securities',
sch13d:'https://www.sec.gov/newsroom/press-releases/2023-219',
hsr:'https://www.ftc.gov/news-events/news/press-releases/2026/01/ftc-announces-2026-update-jurisdictional-fee-thresholds-premerger-notification-filings',
r5110:'https://www.finra.org/rules-guidance/rulebooks/finra-rules/5110',
r5121:'https://www.finra.org/rules-guidance/rulebooks/finra-rules/5121',
r5130:'https://www.finra.org/rules-guidance/rulebooks/finra-rules/5130',
r5150:'https://www.finra.org/rules-guidance/rulebooks/finra-rules/5150',
regm:'https://www.sec.gov/rules-regulations/staff-guidance/trading-markets-frequently-asked-questions/regulation-m',
sec11:'https://www.law.cornell.edu/uscode/text/15/77k',
sox:'https://www.sec.gov/about/laws/soa2002.pdf',
ch11:'https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-basics/chapter-11-bankruptcy-basics',
s4:'https://www.sec.gov/files/forms-4.pdf',
regfd:'https://www.sec.gov/rules-regulations/2000/08/selective-disclosure-insider-trading',
values:'https://www.sportico.com/business/finance/2025/2025-sports-team-values-wnba-f1-mlb-mls-1234879673/',
mlb:'https://www.cnbc.com/2026/09/02/the-los-angeles-angels-are-being-sold-for-a-record-4-billion-heres-what-every-mlb-team-is-now-worth.html',
nflpe:'https://www.cliffordchance.com/content/dam/cliffordchance/briefings/2024/09/financial-investors-in-the-nfl.pdf',
nbape:'https://www.cliffordchance.com/briefings/2026/01/from-five-to-eight--nba-further-loosens-private-equity-ownership.html',
finalis:'https://www.finalis.com/series-79-sponsorship'
};
Object.assign(sources,FOUND_SOURCES);
const examLessons=[
// ===== FUNCTION 1 (49%) =====
['Three statements that talk to each other','1','1.2','Balance sheet, income statement, cash flow: one system.','The income statement measures a period. The balance sheet is a snapshot. The cash flow statement reconciles the two. Net income flows to retained earnings and starts the cash flow statement. Depreciation and amortization reduce income but not cash, so they are added back. Capital expenditures appear in investing cash flow and build PP&E. Borrowing and repayment, dividends and buybacks sit in financing cash flow. Changes in working capital, such as receivables and deferred revenue, bridge accrual profit to cash.','A hypothetical minor-league club sells season tickets in January for games played April through September. Cash arrives early, so deferred revenue rises and operating cash flow runs ahead of revenue. Revenue is recognized game by game. A banker reading only the income statement would miss the seasonal cash cushion; a banker reading only cash would overstate first-quarter performance.','Unlevered FCF = EBIT × (1 − t) + D&A − capex − Δ net working capital','EBITDA is not cash flow. It ignores capex, working capital and taxes, all of which a buyer must fund.','outline'],
['Ratios bankers actually use','1','1.2','Liquidity, profitability and leverage, side by side.','Liquidity: current ratio, quick ratio, cash conversion cycle. Profitability: gross, operating and net margins, ROE, ROA, ROIC. Leverage: net debt to EBITDA and interest coverage. EBITDAR adds back rent so that a company that leases its facilities can be compared with one that owns them. Normalize earnings by removing nonrecurring items before computing any multiple. CAGR describes growth across several years on a compounded basis.','Two hypothetical arena teams each report $60m EBITDA. One owns its building; the other pays $25m a year in arena rent. On EBITDAR the tenant shows $85m. A lender sizing a facility against EBITDA alone would under-lend to the tenant relative to its true operating earnings, while a buyer would over-pay if it forgot the rent obligation.','Net debt = total debt − cash; Interest coverage = EBIT ÷ interest expense','Compare EBITDAR only with EBITDAR. Mixing a tenant’s EBITDA with an owner’s EBITDAR hides a large recurring obligation.','outline'],
['Enterprise value and equity value','1','1.2','What the whole business is worth versus what the shareholders get.','Equity value is share price times diluted shares. Enterprise value adds debt, preferred stock and non-controlling interests and subtracts cash and equivalents. Pair EV with metrics that belong to all capital providers: revenue, EBITDA, EBIT. Pair equity value with metrics that belong to shareholders: net income, book value, dividends. Diluted shares use the treasury stock method for in-the-money options and warrants.','Professional teams are typically quoted on EV to revenue because operating profit is thin or negative. Reported 2025 league averages were roughly 6x revenue for MLB, 9x for the NHL, 10x for the NFL and 12x for the NBA; a control sale of the Boston Celtics was reported near 15x revenue. A buyer paying $1bn for a team that carries $300m of league-approved debt is paying $700m for the equity, not $1bn.','EV = equity value + debt + preferred + non-controlling interest − cash','EV ÷ net income is meaningless. Never pair an enterprise numerator with an equity denominator.','values'],
['DCF and the cost of capital','1','1.2','Project the cash, then discount it at a rate that reflects who is funding it.','Unlevered free cash flow is discounted at the weighted average cost of capital to produce enterprise value. Cost of equity comes from CAPM: risk-free rate plus beta times the equity risk premium. Cost of debt is after tax because interest is deductible. Terminal value uses either a perpetuity growth rate or an exit multiple, and often represents most of the total. A mid-year convention assumes cash arrives evenly through each year.','A hypothetical regional sports network has a fixed rights contract with 4% annual escalators for ten years. Its DCF is dominated by the terminal value assumption: does the contract renew, and at what step-up? Moving the perpetuity growth rate from 2% to 3% with a 9% WACC raises terminal value by about 17%. The banker’s job is to show that sensitivity, not hide it.','WACC = E/V × Re + D/V × Rd × (1 − t);  TV = FCF₍n+1₎ ÷ (WACC − g)','The perpetuity growth rate must be below the discount rate. Growth at or above WACC produces an infinite or negative value.','outline'],
['Comparable companies and precedent transactions','1','1.1','Relative valuation: trading multiples and control multiples.','Trading comps apply current market multiples of similar public companies to the target’s LTM or forward metrics. Precedent transactions apply multiples paid in past control deals, which include a control premium and reflect the financing environment at the time. Peers are chosen on sector, size, growth and margins. Use medians to resist outliers. Calendarize fiscal years that end on different dates. Present the range on a football field chart alongside DCF.','Reported 2026 precedents: the Los Angeles Angels agreed to sell at about 10x revenue, above the roughly 8x paid for the San Diego Padres. A sell-side banker for a third club would argue from those control multiples; a buyer would point to trading multiples of listed sports parents such as Atlanta Braves Holdings or Manchester United, which lack a control premium and trade with public-market liquidity.','Implied EV = peer median multiple × target metric;  Premium = (offer − unaffected price) ÷ unaffected price','Precedents already contain control premiums. Adding a premium on top double counts.','mlb'],
['Accretion, dilution and exchange ratios','1','1.2','Does the deal raise or lower the buyer’s earnings per share?','Pro forma net income equals acquirer income plus target income plus after-tax synergies minus after-tax interest on new acquisition debt minus after-tax interest lost on cash spent. Pro forma shares equal acquirer shares plus any new shares issued. In an all-stock deal, if the acquirer’s P/E exceeds the target’s P/E the deal is accretive. In a cash deal, compare the target’s earnings yield with the after-tax cost of the funding. A fixed exchange ratio shifts price risk to the target’s holders; a floating ratio shifts it to the acquirer; collars limit both.','A hypothetical listed ticketing platform at 30x earnings buys a sports-data company at 20x for stock. Because it pays with a more expensive currency, the deal is accretive before synergies. If the target were priced at 40x, the same deal would be dilutive and the banker would have to justify it with synergies or strategic value.','All-stock: accretive if acquirer P/E > target P/E.  Cash: accretive if target earnings yield > after-tax cost of debt','Accretion is an accounting outcome, not proof of value creation. Overpaying with expensive stock can still be accretive.','outline'],
['Exchange Act filings and ownership data','1','1.1','Where bankers get the numbers, and what each filing tells you.','Form 10-K is the annual report, Form 10-Q the quarterly, Form 8-K a current report due within four business days of a triggering event. The proxy statement (DEF 14A) discloses compensation, governance and shareholder votes. Schedule 13D is filed by an active holder crossing 5% within five business days, with amendments within two business days; Schedule 13G is the passive alternative. Form 13F lists holdings of institutional managers over $100m each quarter. Section 16 insiders, including holders above 10%, report trades on Form 4 within two business days. Regulation FD bars selective disclosure. FINRA Rule 2241 walls research off from banking.','Listed sports parents such as Madison Square Garden Sports, Atlanta Braves Holdings, Liberty Media (Formula 1) and Manchester United file all of these. Their 10-Ks disclose media contracts, arena leases and revenue sharing that private team owners never publish, which makes them the anchor for public comps in a private team valuation.','8-K: 4 business days · 13D: 5 business days · 13D amendment: 2 business days · Form 4: 2 business days','The Schedule 13D deadline changed in February 2024 from 10 calendar days to 5 business days. Older prep material is wrong.','sch13d'],
['Due diligence, Section 11 and Sarbanes-Oxley','1','1.3','Verify the story before anyone signs.','Sell-side diligence assembles the data room and index, monitors access and vets buyers. Buy-side diligence tests financials, contracts, leadership, culture, labor and off-balance-sheet exposure, then feeds negotiating positions. Bring-down diligence updates everything at pricing and closing. Under Securities Act Section 11, the issuer is strictly liable for material misstatements in a registration statement; underwriters and directors escape only with the due diligence defense of a reasonable investigation, judged under Rule 176. Sarbanes-Oxley Section 302 requires officer certifications, 404 an internal-control assessment, 402 bans most executive loans, 403 accelerates insider transaction reports.','Diligence on a hypothetical franchise sale centers on items a normal company lacks: the league constitution and approval conditions, revenue-sharing and luxury-tax exposure, the arena lease and naming-rights term, media contracts with change-of-control clauses, the collective bargaining agreement, and related-party deals between the club and the owner’s other businesses.','Section 11 due diligence defense: a reasonable investigation and reasonable ground to believe the statements were true (Rule 176)','The issuer has no due diligence defense. Underwriters do, but only if they actually investigated rather than relied on management.','sec11'],
// ===== FUNCTION 2 (27%) =====
['Registration and the public offering timeline','2','2.1','Section 5 and the three periods every banker memorizes.','Pre-filing period: no offers of any kind. Rule 135 allows a bare-facts announcement; Rules 168 and 169 protect regularly released factual information; Rule 163A gives a 30-day safe harbor for communications before filing; well-known seasoned issuers may make offers under Rule 163. Waiting period: oral offers, the preliminary prospectus (red herring, Rule 430), tombstone ads (Rule 134), road shows and free writing prospectuses (Rules 164 and 433). Post-effective period: sales, with final prospectus delivery. Rule 430A lets pricing be omitted until effectiveness; the priced prospectus is filed under Rule 424(b). Rule 415 shelf registration lets S-3 eligible issuers take securities down over three years; WKSIs get automatic shelves. Emerging growth companies under the JOBS Act may file confidentially and test the waters.','A hypothetical sports-betting technology company plans an IPO. Its CEO gives a magazine interview about “huge upcoming investor demand” two weeks before the S-1 is filed. That is gun-jumping: an unregistered offer that can force a cooling-off period and create Section 12 rescission liability. The same company, once public, could later use a shelf to raise follow-on equity in a single afternoon.','Pre-filing: no offers · Waiting: offers, no sales · Post-effective: sales with prospectus','Anything that conditions the market before filing can be an illegal offer. Rule 135 notices are limited to name, amount, timing and purpose.','outline'],
['Syndicate, pricing and stabilization','2','2.2','How the deal is committed, split, priced and supported.','Firm commitment: underwriters buy the issue and bear the risk. Best efforts: agents sell what they can; all-or-none and mini-max variants require escrow under Rule 15c2-4 and honest representations under Rule 10b-9. Standby underwriting backs a rights offering. The agreement among underwriters and the selected dealers agreement allocate liability and economics. The gross spread splits roughly into management fee, underwriting fee and selling concession. The over-allotment option, or greenshoe, is capped at 15% by FINRA Rule 5110, which also governs underwriting compensation. Rule 5121 requires a qualified independent underwriter when the member has a conflict. Rule 5130 bars restricted persons from buying new-issue equity. Regulation M limits bids and purchases by distribution participants during the restricted period, allows stabilizing bids only at or below the offering price (Rule 104), and bars covering with offering shares after a short sale in the five days before pricing (Rule 105).','A hypothetical $300m sports-streaming IPO prices at $20. Demand is soft, so the syndicate sells 15% more shares than the base deal, creating a short position. If the stock trades to $19, the syndicate buys in the market to cover, supporting the price. If it trades to $23, the syndicate exercises the greenshoe and buys the shares from the issuer at the offering price instead.','Gross spread = public offering price − proceeds to issuer; typical split 20% management, 20% underwriting, 60% selling concession','A stabilizing bid may never be above the public offering price. Syndicate short covering, not stabilizing bids, is the usual support tool.','r5110'],
['Exempt offerings and private placements','2','2.6','Raising capital without registration, and what the 79 does and does not let you do.','Section 4(a)(2) exempts issuer transactions not involving a public offering. Regulation D provides safe harbors: Rule 504 up to $10m; Rule 506(b) unlimited, no general solicitation, up to 35 non-accredited but sophisticated purchasers; Rule 506(c) general solicitation permitted if every purchaser is a verified accredited investor. Form D is filed within 15 days of first sale. Accredited investors include individuals with $200k income ($300k joint), $1m net worth excluding the primary residence, or Series 7, 65 or 82 licenses. Rule 144 governs resales of restricted and control securities: six-month holding period for reporting issuers, one year otherwise, plus volume limits for affiliates. Rule 144A allows resales to qualified institutional buyers with at least $100m in discretionary investments. Regulation S covers offshore offerings; Regulation A permits mini-public offerings up to $75m. FINRA Rule 5123 requires members to file private placement documents.','Minority limited-partner stakes in professional teams are sold as private placements to accredited investors and qualified purchasers, increasingly to approved private equity funds. The Investment Banking Representative may structure the offering, draft the private placement memorandum and term sheet, and advise on eligibility. Actively marketing it to investors on a road show requires an additional General Securities (Series 7) or Private Securities Offerings (Series 82) registration.','506(b): no general solicitation, ≤35 non-accredited · 506(c): solicit publicly, all purchasers verified · Form D within 15 days','Series 79 covers advising and structuring. Investor-facing marketing needs Series 7 or Series 82 on top.','regd'],
['Financing alternatives and league capital rules','2','2.6','Debt, equity and hybrids, plus the constraints only sports imposes.','Senior secured debt is cheapest; unsecured, subordinated and mezzanine debt cost more; preferred stock and common equity cost most. Convertibles and warrants blend debt and equity. PIPEs place public company shares privately. Primary offerings raise money for the company; secondary offerings sell existing holders’ shares. Entity choice matters: C corporations face double taxation; S corporations, LLCs and partnerships pass income through; REITs and MLPs are pass-through vehicles with asset tests. Investor types differ by regulation: qualified institutional buyers ($100m) for 144A, qualified purchasers ($5m of investments) for 3(c)(7) funds, accredited investors for Regulation D.','Leagues cap leverage and ownership. Reported rules as of 2025 and 2026: the NFL limits team debt to about $1.4bn, requires a controlling owner with at least 30%, and permits approved private equity funds to own up to 10% of a club with a six-year hold. The NBA, NHL and MLS allow up to 20% per fund and 30% in aggregate, and the NBA raised the number of teams a fund may hold from five to eight in December 2025. A capital structure that clears a lender’s model can still fail league approval.','Cost of capital ranking: senior secured < unsecured < subordinated < preferred < common','Team transactions are constrained by league debt ceilings and ownership caps that override any financing model. Check the constitution before the spreadsheet.','nbape'],
// ===== FUNCTION 3 (24%) =====
['Sell-side M&A from engagement to signing','3','3.1','Running the auction.','The engagement letter sets the retainer, success fee, tail period, exclusivity and indemnity. Structure choices: sale of the whole company, divestiture, tax-free spin-off, split-off. Stock sale versus asset sale drives tax: buyers prefer assets for a stepped-up basis; sellers prefer stock for a single layer of tax; a Section 338(h)(10) election can give asset treatment to a stock sale of a subsidiary or S corporation. Section 280G taxes golden parachutes above three times base compensation. Process: teaser, confidentiality agreement, confidential information memorandum, bidding procedures letter, indications of interest, management presentations, data room, final bids, letter of intent or definitive agreement, fairness opinion if requested. Hart-Scott-Rodino filings apply above the size-of-transaction threshold ($133.9m for 2026) with a 30-day waiting period, 15 days for cash tender offers.','A hypothetical NBA club runs a targeted rather than broad auction: the league must approve the buyer, a controlling owner must meet net-worth tests, and confidentiality matters to sponsors and players. The banker vets bidders for capacity to pay and league acceptability before the CIM goes out, and the definitive agreement conditions closing on a league vote.','Sell-side sequence: engage → teaser → NDA → CIM → IOI → management meetings → final bids → definitive agreement → regulatory and league approvals → close','A C-corporation asset sale gives the buyer a basis step-up but the seller two layers of tax. The price must reflect who bears it.','hsr'],
['Buy-side M&A, hostile approaches and defenses','3','3.2','Valuing the target from the buyer’s chair.','Buy-side work starts with the buyer’s strategy and capacity: cash, debt capacity and stock as currency. Value the target stand-alone with comps, precedents, DCF and an LBO, then pro forma with synergies. Strategic buyers can pay for synergies; financial sponsors pay what a target IRR allows. Financing commitment letters and stapled financing shape bids. Impediments include poison pills (shareholder rights plans), staggered boards, supermajority and fair-price provisions, and state control-share statutes. Hostile tactics: bear hug letters, tender offers and proxy fights. Defenses: white knight, crown-jewel sale, Pac-Man. Once a board decides to sell for cash, Delaware’s Revlon doctrine requires it to seek the best price reasonably available.','Hostile takeovers of franchises are effectively impossible: league constitutions require owner votes on any transfer of control. Hostile tactics matter for sports-adjacent public companies such as media, ticketing and betting platforms, where a buyer can go directly to shareholders with a tender offer if the board refuses to engage.','Strategic ceiling ≈ stand-alone value + PV of synergies − integration cost;  Sponsor ceiling ≈ price that still clears the target IRR','Synergies belong to the buyer. Paying all of them to the seller in the purchase price leaves no value creation for the buyer’s shareholders.','outline'],
['Tender offers, going private and shareholder votes','3','3.5','The Williams Act clock, and the merger alternative.','A bidder files Schedule TO when a tender offer commences. Under Rule 14e-1 the offer stays open at least 20 business days and at least 10 business days after any change in price or percentage sought. In April 2026 the SEC permitted a 10-business-day minimum for offers made under a negotiated merger agreement for all shares of the class. The target must state its position on Schedule 14D-9 within 10 business days. Rule 14d-10 requires the offer to be open to all holders at the best price paid to any. Rule 14e-3 prohibits trading on material nonpublic information about a tender offer without any need to prove a breach of duty. Rule 14e-5 bars purchases outside the offer. Rule 13e-3 adds fairness disclosure to going-private deals by affiliates; Rule 13e-4 governs issuer self-tenders. Mergers use a proxy statement under Regulation 14A, and Form S-4 when stock is consideration; Rules 165 and 425 govern deal communications.','A hypothetical public sports-media company agrees to be acquired at $40 a share through a negotiated tender offer for all shares. Under the 2026 order the offer could close in as few as 10 business days. An employee who learns of the pending offer and buys call options violates Rule 14e-3 even without a fiduciary relationship to the source.','Schedule TO at start · ≥20 business days (10 for qualifying negotiated all-share offers since April 2026) · +10 business days after any change · 14D-9 within 10 business days','Rule 14e-3 is broader than Rule 10b-5: in the tender offer context, trading on material nonpublic information is illegal without any breach of duty.','tender2026'],
['Fairness opinions, restructuring and bankruptcy','3','3.6','When the deal needs an independent view, and when the company cannot pay.','FINRA Rule 5150 requires a fairness opinion to disclose whether the member will receive compensation contingent on completion, relationships with the parties in the past two years, whether an internal fairness committee approved it, and whether the member independently verified information. A fairness opinion states that consideration is fair from a financial point of view; it is not a recommendation. In restructuring, the absolute priority rule orders recoveries: secured creditors, administrative and priority claims, unsecured creditors, subordinated debt, preferred, then common. The fulcrum security is the class that converts to equity. Chapter 11 reorganizes with the debtor in possession, a creditors’ committee, debtor-in-possession financing with super-priority, a 120-day exclusivity period for the plan, cramdown of dissenting classes and Section 363 asset sales, often with a stalking-horse bidder. Chapter 7 liquidates through a trustee. Credit agreements carry maintenance and incurrence covenants, events of default and prepayment premiums.','The Texas Rangers were sold through a Section 363 bankruptcy auction in 2010 after the owner’s lenders and Major League Baseball disagreed on a private sale. Bankruptcy auctions give the buyer clean title and court approval, but the league still had to approve the winning bidder. Distressed situations are rarer among major-league teams than among venues, minor-league clubs and start-up leagues.','Recovery waterfall: senior secured → DIP and administrative → unsecured → subordinated → preferred → common','A fairness opinion is not a guarantee of the best price. Contingent fees must be disclosed under Rule 5150.','r5150']
].map((x,i)=>({id:i,title:x[0],f:x[1],task:x[2],sub:x[3],body:x[4],example:x[5],formula:x[6],trap:x[7],source:x[8]}));
const NF=FOUND_LESSONS.length;
const lessons=[...FOUND_LESSONS.map((x,i)=>({id:i,title:x[0],f:'0',task:'Foundations',sub:x[1],body:x[2],example:x[3],formula:x[4],trap:x[5],source:x[6],needs:[]})),...examLessons.map(l=>({...l,id:l.id+NF,needs:(NEEDS[l.id]||[])}))];

const raw=[
[0,"A company reports $50m net income, $12m depreciation, a $6m increase in receivables and $9m of capital expenditures. Ignoring other items, cash flow after capex is closest to:",["$47m","$65m","$41m","$77m"],0,"Start with $50m, add back $12m non-cash depreciation, subtract the $6m working-capital build and $9m capex: $47m."],
[0,"Season-ticket cash collected before games are played appears on the balance sheet as:",["Accounts receivable","Deferred revenue, a liability","Retained earnings","Prepaid expense"],1,"Cash received before performance is a liability to deliver the games. Revenue is recognized as they are played."],
[0,"Which item reduces net income but does not reduce cash in the period?",["Interest paid","Inventory purchase","Amortization of intangibles","Dividend paid"],2,"Amortization is a non-cash charge and is added back in operating cash flow."],
[0,"Unlevered free cash flow starts from EBIT rather than net income because:",["EBIT is always larger","Interest is not tax deductible","Net income is not audited","EBIT excludes financing costs, so the cash flow belongs to all capital providers"],3,"Unlevered cash flow is pre-interest so it can be discounted at WACC and valued for debt and equity holders together."],
[1,"A team has $60m EBITDA, $25m arena rent and $200m debt with $20m cash. Net debt to EBITDAR is:",["2.1x","3.6x","1.5x","3.0x"],0,"Net debt is $180m. EBITDAR is $85m. $180m ÷ $85m = 2.1x."],
[1,"EBIT is $40m and interest expense is $16m. Interest coverage is:",["4.0x","2.5x","16x","0.4x"],1,"$40m ÷ $16m = 2.5x. Coverage below about 2x usually signals stress to lenders."],
[1,"Revenue grows from $100m to $146m over four years. The CAGR is closest to:",["7.7%","11.5%","9.9%","46%"],2,"(146 ÷ 100)^(1/4) − 1 ≈ 9.9%. Dividing 46% by four ignores compounding."],
[1,"Before applying an EV/EBITDA multiple, a banker should first:",["Convert to LIFO","Subtract capex","Add back all interest","Remove nonrecurring items to normalize EBITDA"],3,"Multiples assume a recurring earnings base. One-time gains or charges distort the implied value."],
[2,"Market cap $800m, debt $300m, preferred $50m, cash $100m. Enterprise value is:",["$1,050m","$950m","$1,150m","$1,250m"],0,"800 + 300 + 50 − 100 = $1,050m."],
[2,"Which pairing is internally consistent?",["Equity value ÷ EBITDA","EV ÷ EBIT","EV ÷ dividends","EV ÷ net income"],1,"EBIT is before interest, so it belongs to all capital providers, matching EV. Net income and dividends belong to equity."],
[2,"A team sells for a $1,000m enterprise value carrying $300m of debt and $20m cash. The seller’s equity proceeds before fees are:",["$1,280m","$1,000m","$720m","$680m"],2,"Equity = EV − debt + cash = 1,000 − 300 + 20 = $720m."],
[2,"A company has 100m shares at $10 and 10m options with a $6 strike. Diluted shares under the treasury stock method are:",["106m","100m","110m","104m"],3,"Options bring in $60m, which repurchases 6m shares at $10. Net new shares are 4m, so 104m."],
[3,"Risk-free 4%, beta 1.2, equity risk premium 5%. Cost of equity is:",["10%","6%","13%","9%"],0,"4% + 1.2 × 5% = 10%."],
[3,"Equity is 70% of capital at a 10% cost; debt is 30% at 6% pre-tax; tax rate 25%. WACC is:",["8.8%","8.35%","7.0%","9.2%"],1,"0.7 × 10% + 0.3 × 6% × 0.75 = 7.0% + 1.35% = 8.35%."],
[3,"Final-year FCF is $50m, growth 2%, WACC 9%. Terminal value using the perpetuity method is closest to:",["$2,500m","$714m","$729m","$556m"],2,"$50m × 1.02 ÷ (0.09 − 0.02) = $728.6m. Grow the cash flow one year first."],
[3,"Raising the assumed perpetuity growth rate while holding WACC constant will:",["Not affect terminal value","Raise WACC","Lower terminal value","Raise terminal value"],3,"A smaller denominator (WACC − g) and a larger numerator both push terminal value up."],
[4,"Precedent transaction multiples usually exceed trading multiples for similar companies because they:",["Include a control premium","Exclude debt","Are based on book value","Use forward metrics"],0,"Buyers pay a premium for control and synergies; public trading prices reflect minority stakes."],
[4,"Peer median EV/revenue is 9x. A team’s revenue is $400m and it carries $500m net debt. Implied equity value is:",["$3,600m","$3,100m","$4,100m","$3,500m"],1,"EV = 9 × 400 = $3,600m. Subtract $500m net debt: $3,100m equity."],
[4,"An offer of $52 per share is made when the unaffected price is $40. The premium is:",["52%","23%","30%","12%"],2,"(52 − 40) ÷ 40 = 30%."],
[4,"When peers have different fiscal year ends, a banker should:",["Use book value instead","Use only the largest peer","Ignore the difference","Calendarize the financials to a common period"],3,"Calendarization aligns LTM or forward figures so multiples compare like periods."],
[5,"An acquirer at 25x earnings buys a target at 15x in an all-stock deal with no synergies. The deal is:",["Accretive","Neutral","Impossible to tell","Dilutive"],0,"The acquirer pays with a currency valued more richly than the earnings it buys, so pro forma EPS rises."],
[5,"A cash acquisition funded with 6% debt at a 25% tax rate buys a target with a 5% earnings yield. Before synergies the deal is:",["Dilutive","Accretive","Neutral","Tax-free"],1,"After-tax cost of debt is 6% × (1 − 0.25) = 4.5%. The target’s 5% earnings yield exceeds that funding cost, so pro forma EPS rises."],
[5,"Acquirer shares 200m, target shares 100m, exchange ratio 0.5. Pro forma shares are:",["400m","300m","250m","150m"],2,"100m × 0.5 = 50m new shares. 200m + 50m = 250m."],
[5,"A fixed exchange ratio between signing and closing places the risk of a falling acquirer share price on:",["Neither party","The exchange","The acquirer’s shareholders","The target’s shareholders"],3,"Target holders receive a fixed number of shares, so their consideration falls with the acquirer’s price."],
[6,"An activist crosses 5% of a listed company on Monday and intends to seek board changes. Schedule 13D is due:",["Within 5 business days","Within 45 days","Only at year end","Within 10 calendar days"],0,"Since February 2024, initial Schedule 13D is due within five business days; amendments within two."],
[6,"A company signs a definitive merger agreement. The Form 8-K is due within:",["2 business days","4 business days","15 days","30 days"],1,"Most 8-K items are due within four business days of the triggering event."],
[6,"Which filing discloses executive compensation and matters put to a shareholder vote?",["Form 10-Q","Schedule 13F","DEF 14A proxy statement","Form 8-K"],2,"The proxy statement is the governance document for annual and special meetings."],
[6,"Regulation FD is violated when:",["A 10-K is filed late","An underwriter shorts stock","A director buys shares","A CEO discloses material nonpublic information to a selected analyst without simultaneous public disclosure"],3,"Reg FD requires public disclosure of material information shared with market professionals or holders likely to trade."],
[7,"Under Section 11 of the Securities Act, which party has no due diligence defense?",["Issuer","Auditor","Underwriter","Independent director"],0,"The issuer is strictly liable for material misstatements or omissions in the registration statement."],
[7,"An underwriter’s reasonable investigation defense is evaluated under:",["Rule 144","Rule 176","Rule 415","Rule 10b-5"],1,"Rule 176 lists factors bearing on what counts as a reasonable investigation and reasonable ground for belief."],
[7,"Sarbanes-Oxley Section 404 requires:",["Quarterly dividends","A ban on all executive loans","Management assessment of internal control over financial reporting","Two-day insider trade reporting"],2,"Section 404 is the internal-controls assessment; 402 covers loans and 403 insider reports."],
[7,"In a franchise sale, which diligence item is unique to sports?",["Lease schedules","Fixed asset register","Accounts receivable aging","League approval conditions and revenue-sharing obligations"],3,"League constitutions, approval votes and shared revenue have no equivalent in ordinary corporate diligence."],
[8,"During the waiting period an underwriter may:",["Deliver a preliminary prospectus and take indications of interest","Confirm sales","Publish research recommending the IPO","Accept payment for shares"],0,"Offers are permitted after filing; sales and confirmations wait for effectiveness."],
[8,"A CEO’s pre-filing interview predicting strong investor demand for the upcoming IPO is best described as:",["A Rule 135 notice","Gun-jumping","A free writing prospectus","Permitted testing the waters"],1,"It conditions the market before a registration statement exists, an unregistered offer under Section 5."],
[8,"Rule 415 shelf registration allows an eligible issuer to:",["Skip the prospectus","Avoid Section 11 liability","Register securities now and sell them over time, generally up to three years","Sell only to QIBs"],2,"A shelf lets seasoned issuers take securities down quickly through a prospectus supplement."],
[8,"Under Rule 430A, the final prospectus containing pricing information is filed under Rule 424(b) within:",["15 days","30 days","It is never filed","2 business days after pricing"],3,"Rule 424(b) requires filing the priced prospectus no later than the second business day after pricing."],
[9,"In a firm commitment underwriting, unsold shares are:",["Owned by the underwriters","Cancelled","Sold to the SEC","Returned to the issuer"],0,"The underwriters buy the whole issue and bear the risk of unsold securities."],
[9,"A stabilizing bid may be entered:",["Above the offering price to support demand","At or below the public offering price","Only after the greenshoe is exercised","Only by the issuer"],1,"Regulation M Rule 104 caps stabilizing bids at the offering price."],
[9,"FINRA Rule 5121 requires a qualified independent underwriter when:",["Restricted persons buy","The deal exceeds $100m","The member has a conflict of interest, such as an affiliate issuer","The greenshoe is used"],2,"Conflicted offerings need a QIU to participate in due diligence and pricing unless an exception applies."],
[9,"Gross spread is $1.50 on a $20 IPO with a 20/20/60 split. The selling concession per share is:",["$0.60","$1.20","$0.30","$0.90"],3,"60% of $1.50 is $0.90; management and underwriting fees are $0.30 each."],
[10,"Which is permitted under Rule 506(c) but not 506(b)?",["General solicitation, with verified accredited purchasers","Unlimited offering size","Skipping Form D","Selling to 35 non-accredited investors"],0,"506(c) allows advertising but every purchaser must be verified accredited. 506(b) allows up to 35 non-accredited but no solicitation."],
[10,"Form D must be filed within:",["It is optional","15 days of the first sale","2 business days of pricing","45 days of quarter end"],1,"Rule 503 requires Form D no later than 15 calendar days after the first sale."],
[10,"A qualified institutional buyer under Rule 144A generally must own and invest on a discretionary basis at least:",["$5 million","$25 million","$100 million","$1 billion"],2,"The core QIB test is $100m of securities of unaffiliated issuers."],
[10,"Restricted shares of a reporting company acquired in a private placement may be resold under Rule 144 after a holding period of:",["1 year","3 years","30 days","6 months"],3,"Six months for reporting issuers; one year for non-reporting issuers."],
[11,"Which security ranks highest in a liquidation?",["Senior secured debt","Subordinated notes","Common stock","Preferred stock"],0,"Secured lenders have a claim on collateral ahead of every other class."],
[11,"A C corporation’s owners face double taxation because:",["Capital gains are exempt","Dividends are not deductible and are taxed again at the shareholder level","Interest is taxed twice","S corporations pay more"],1,"Corporate income is taxed, then distributed profits are taxed again to shareholders. Pass-through entities avoid the first layer."],
[11,"A private investment in public equity (PIPE) is:",["A tender offer","A registered follow-on offering","A private placement of a public company’s securities","A rights offering"],2,"PIPEs sell public-company securities privately, usually to institutions, often with resale registration rights."],
[11,"Reported NFL rules permit an approved private equity fund to own up to what share of a club?",["30%","49%","100%","10%"],3,"The NFL’s 2024 policy allowed approved funds up to 10%, with minimum stake and holding-period conditions. Other leagues allow more."],
[12,"In a stock sale of a target subsidiary, a Section 338(h)(10) election lets the buyer:",["Treat the purchase as an asset acquisition for tax and step up the basis","Skip a fairness opinion","Defer all tax indefinitely","Avoid HSR filing"],0,"The election gives asset-sale tax treatment while legally transferring stock."],
[12,"Which document typically goes to buyers first in an auction?",["Confidential information memorandum","Teaser","Definitive agreement","Fairness opinion"],1,"A short anonymous teaser gauges interest; the CIM follows a signed confidentiality agreement."],
[12,"Section 280G is concerned with:",["Tender offer timing","Antitrust review","Excess golden parachute payments to executives on a change in control","Tax-free spin-offs"],2,"Payments above three times base compensation trigger loss of deductibility and a 20% excise tax."],
[12,"The 2026 HSR size-of-transaction threshold is approximately:",["$500 million","$1 billion","$50 million","$133.9 million"],3,"The FTC set the 2026 minimum at $133.9m, effective February 17, 2026, with a 30-day waiting period."],
[13,"A shareholder rights plan (poison pill) primarily:",["Dilutes a hostile acquirer that crosses a trigger threshold","Requires a fairness opinion","Blocks all tender offers by law","Guarantees a higher price"],0,"Pills let other holders buy at a discount once a bidder crosses the trigger, making a hostile accumulation prohibitively expensive."],
[13,"A strategic buyer can usually pay more than a financial sponsor because:",["It has no shareholders","It can capture operating synergies","It avoids taxes","It never uses debt"],1,"Synergies raise the value of the target in the strategic buyer’s hands; a sponsor relies on leverage and exit multiple."],
[13,"Once a Delaware board decides to sell the company for cash, Revlon requires it to:",["Adopt a pill","Accept the first offer","Seek the best price reasonably available","Refuse all bids"],2,"Revlon duties shift the board’s role to auctioneer seeking maximum value."],
[13,"Why are hostile takeovers of major-league franchises effectively impossible?",["Antitrust law bans them","Franchises cannot be valued","Teams have no shareholders","League constitutions require owner approval of any transfer of control"],3,"Ownership transfers need a league vote, so a buyer cannot go around the seller."],
[14,"Under the general rule, a third-party tender offer must remain open at least:",["20 business days","60 days","5 business days","10 calendar days"],0,"Rule 14e-1 sets 20 business days; a 2026 SEC order permits 10 for qualifying negotiated all-share offers."],
[14,"A bidder raises its tender price with three days left. The offer must stay open at least:",["3 more days","10 business days from the change","20 more business days","No extension required"],1,"Any change in price or percentage sought requires the offer to remain open 10 business days."],
[14,"The target company must publish its position on a tender offer on Schedule 14D-9 within:",["45 days","2 business days","10 business days","20 business days"],2,"Rule 14e-2 and Schedule 14D-9 require the subject company’s recommendation within 10 business days of commencement."],
[14,"Rule 14e-3 differs from Rule 10b-5 because it:",["Covers only debt securities","Requires a proxy statement","Applies only to issuers","Prohibits trading on nonpublic tender offer information without requiring a breach of duty"],3,"In the tender context, possession of material nonpublic information from the bidder or target is enough."],
[15,"FINRA Rule 5150 requires a fairness opinion to disclose:",["Whether the member’s compensation is contingent on completing the transaction","The names of all bidders","The target’s tax returns","The exact valuation model"],0,"Contingent fees, prior relationships, committee approval and verification of information must all be disclosed."],
[15,"In a Chapter 11 case, debtor-in-possession financing typically receives:",["Equity treatment","Super-priority ahead of existing unsecured claims","No repayment","Subordination to common stock"],1,"DIP lenders are induced with priority claims and often liens to fund operations during the case."],
[15,"The fulcrum security in a restructuring is:",["Trade payables","The most senior debt","The class whose claims convert into the reorganized equity","Common stock"],2,"It is the class where value runs out; holders above are paid in full, holders below are wiped out."],
[15,"A Section 363 sale allows a debtor to:",["Avoid league approval","Cancel all contracts without notice","Issue new registered stock","Sell assets free and clear of liens with court approval, often after an auction"],3,"The 2010 Texas Rangers sale was a 363 auction; the winning bidder still needed Major League Baseball approval."]
];
const foundBank=FOUND_Q.map((x,i)=>({id:i,topic:x[0],q:x[1],choices:x[2],answer:x[3],why:x[4]}));
const bank=[...foundBank,...raw.map((x,i)=>({id:foundBank.length+i,topic:x[0]+NF,q:x[1],choices:x[2],answer:x[3],why:x[4]}))];

const PLAN={
weeksToExam:10,
phases:[
{name:'Start here · Foundations',when:'Weeks 1–2, before anything else',hours:'10–15 hours',why:'The exam lessons assume you can read a balance sheet and know what free cash flow is. If you do not yet, these 14 short lessons build that from zero, one idea at a time, in plain English with a sports example each.',steps:['Read Foundations 1 to 6 in order: what a business is, the balance sheet, the income statement, depreciation, EBITDA, cash flow','Read Foundations 7 to 11: debt, equity, time value of money, valuation, risk and the cost of capital','Read Foundations 12 to 14: what bankers do, what the SEC and FINRA are, and how to decode a deal headline','Answer the two check questions after every foundation lesson; re-read any lesson you miss','Tap any dotted term in a lesson to see its definition; use the Glossary page when a word stops you']},
{name:'Phase 0 · SIE first',when:'Weeks 1–3',hours:'25–40 hours',why:'The SIE is the corequisite, needs no sponsor, and is valid for four years. Passing it also makes you a more credible candidate to a sponsoring firm.',steps:['Register on FINRA’s site and schedule a Prometric date three weeks out','Study the SIE outline: products, markets, regulation, prohibited practices','Two full-length timed practice exams above 80% before test day','Book the exam: 75 scored questions, 105 minutes, 70% to pass']},
{name:'Phase 1 · Sponsorship and the registration decision',when:'Weeks 1–4, in parallel',hours:'Conversations, not study',why:'You cannot sit for the Series 79 without a FINRA member firm filing Form U4 for you. Decide the route before you study.',steps:['Write a one-page description of the deals you intend to do: private teams, minority stakes, agencies, venues, media, public companies','Take it to two or three sports-focused boutiques and two platform broker-dealers that sponsor independent bankers','Ask compliance whether any of your intended work falls under the federal M&A broker exemption and how your operating states treat it','Confirm whether you will also market placements to investors; if so, plan for Series 82 or Series 7 as an add-on']},
{name:'Phase 2 · Function 1 (49%)',when:'Weeks 4–7',hours:'35–45 hours',why:'Nearly half the exam is financial statement analysis, valuation and filings. This is where candidates fail.',steps:['Exam lessons 1–8 in this room, one per session, formula reproduced from memory; open the Before-you-read links whenever a term is fuzzy','Build a one-page DCF and a one-page accretion/dilution model in a spreadsheet by hand','Drill the filing deadlines table daily until automatic','Function 1 questions in timed mode; target 80% before moving on']},
{name:'Phase 3 · Function 2 (27%)',when:'Weeks 7–8',hours:'15–20 hours',why:'Registration periods, syndicate mechanics and exempt offerings are rule-dense but predictable.',steps:['Exam lessons 9–12; draw the Section 5 timeline from memory','Memorize Reg D, Rule 144, 144A and Reg M numbers as a single card','Practice spread and greenshoe arithmetic']},
{name:'Phase 4 · Function 3 (24%)',when:'Weeks 8–9',hours:'15–20 hours',why:'Your future job. Learn it as process, then as rules.',steps:['Exam lessons 13–16; write the sell-side sequence and the tender offer clock on one page','Read one real merger proxy (Schedule 14A) and one Schedule TO on EDGAR end to end','Read FINRA Rule 5150 in full']},
{name:'Phase 5 · Full-length practice and exam',when:'Week 10',hours:'10–15 hours',why:'Endurance and pacing: 80 questions in 150 minutes is under two minutes each.',steps:['Two full mixed sessions of all 64 questions here, then two full-length exams from a comprehensive provider','Review every missed question and re-read the lesson it belongs to','Schedule the Series 79 once your sponsor has filed the U4 and opened the exam window']}
],
beyond:['This room’s 64 questions cover the skeleton of the outline. Before the exam add a full-length bank of 1,000 or more questions from a comprehensive provider.','Topics this room only touches: detailed Regulation S-K and S-X items, Reg M restricted-period arithmetic, Rule 5110 compensation components, Regulation A tiers, Rule 147A, Form CRS, syndicate settlement timing, detailed proxy rules and DGCL merger sections.','Study the actual Series 79 outline task by task. Every bullet on it is fair game.']
};

const LICENSE={
routes:[
{title:'Route A · Registered Investment Banking Representative (SIE + Series 79)',fit:'Best fit for the work you described',body:'Advising and facilitating M&A, tender offers, restructurings, asset sales, divestitures and debt or equity offerings, whether the client is public or private, buy-side or sell-side. Sponsorship by a FINRA member is required; many independent bankers affiliate with a platform broker-dealer rather than build their own. Add Series 82 or Series 7 if you will actively market private placements to investors, and Series 24 later if you supervise or run the firm.'},
{title:'Route B · Federal M&A broker exemption (no FINRA registration)',fit:'Possible for part of the work, never for all of it',body:'Since March 29, 2023, Exchange Act Section 15(b)(13) exempts brokers who only effect securities transactions in the transfer of ownership of a privately held company with under $25m EBITDA or under $250m revenue, where the buyer gains control (presumed at 25% voting power) and actively operates the business. The exemption is lost if you hold client funds, arrange financing without disclosure, facilitate a public offering, help form a buyer group, deal with passive investors or shell companies. It does not preempt state law: about 23 states had adopted parallel relief as of April 2025 and terms differ. Most major-league franchises exceed the revenue test, and minority LP stakes fail the control test.'},
{title:'Route C · Series 7 alone',fit:'Not the right primary license',body:'The General Securities Representative registration covers sales and trading with customers. FINRA requires the Series 79 rather than the Series 7 for anyone whose job is the investment banking functions above. Series 7 becomes relevant only as an add-on for investor-facing marketing.'}
],
deals:[
['Control sale of a major-league franchise','Revenue usually exceeds $250m: no exemption. Registered rep at a member firm.'],
['Minority LP stake in a team placed with private equity or family offices','Buyer is passive, not in control: no exemption. Series 79 to structure and advise; Series 82 or 7 to market to investors.'],
['Sale of a sports agency, youth-sports operator or venue business with $8m EBITDA to a strategic buyer taking 100%','Federal exemption available; check each state involved. Registration still the cleaner path if you do any other deal type.'],
['Advising a listed sports-media company on a tender offer','Public company: no exemption. Registered rep required.'],
['Raising debt for a stadium project','Placement of securities to investors: registered rep; marketing to investors needs 82 or 7.']
]
};
